**1. Business Objective Alignment**

• **Objective:**
Transform raw academic and performance indicators into
model-ready structured features.

• **Business Relevance:**
Ensure data is standardized, scalable, and suitable
for risk classification modeling.

**2. Import Required Libraries**

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.utils import resample

**3. Load Dataset**

In [3]:
df = pd.read_csv("/content/sample_data/employability_prediction_data.csv")

df.head()

,CGPA,Aptitude_Score,Technical_Score,Communication_Score,Internships,Backlogs,Certifications,Employable
0,6.87,80,59,57,3,2,0,0
1,9.75,77,50,50,4,0,5,0
2,8.66,48,91,65,0,5,5,0
3,7.99,35,39,53,1,0,2,0
4,5.78,56,42,83,2,0,5,0

**4. Separate Features & Target**

In [4]:
X = df.drop("Employable", axis=1)
y = df["Employable"]

**5. Train-Test Split**

In [5]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

X_train.shape, X_test.shape

((4000, 7), (1000, 7))

**6. Feature Scaling**

This dataset contains numerical columns only:
CGPA ,Aptitude_Score,Technical_Score ,Communication_Score ,Internships, Backlogs, Certifications

All numeric → scaling required.

In [6]:
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

**7. Class Imbalance Check**

In [7]:
y_train.value_counts(normalize=True)

Employable
0    0.8975
1    0.1025
Name: proportion, dtype: float64

Dataset shows moderate balance. Advanced imbalance handling (e.g., SMOTE) will be evaluated during modeling phase if required.

**8. Feature Importance Pre-Check (Tree-Based Quick Test)**

In [8]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(random_state=42)
rf.fit(X_train, y_train)

importances = pd.Series(rf.feature_importances_, index=X.columns)
importances.sort_values(ascending=False)

Backlogs               0.251125
Technical_Score        0.242374
Aptitude_Score         0.239450
CGPA                   0.230067
Communication_Score    0.020815
Internships            0.008099
Certifications         0.008071
dtype: float64

**9. Save Preprocessed Data**

In [10]:
import os
import joblib

# Ensure src directory exists
os.makedirs("../src", exist_ok=True)

# Save scaler
joblib.dump(scaler, "../src/scaler.pkl")

['../src/scaler.pkl']

**10. Final Output Summary**

**Feature Engineering Summary**

• Performed stratified train-test split to preserve class distribution.

• Applied standardization to normalize feature scale.

• Evaluated preliminary feature importance using Random Forest.

• Prepared scaled datasets for ML and Deep Learning pipelines.

• Ensured model-ready structured inputs.